#!/usr/bin/env python
# coding=utf-8

# https://nsrc.org/workshops/2009/summer/presentations/day3/common-ports.pdf

COMMON_PORTS = { 7 : 'echo',
                19 : 'chargen',
                20 : 'ftp',
                21 : 'ftp',
                22 : 'ssh',
                23 : 'telnet',
                25 : 'smtp',
                42 : 'WINS',
                43 : 'whois',
                49 : 'tacacs',
                53 : 'dns',
                67 : 'dhcp/bootp',
                68 : 'dhcp/bootp',
                69 : 'tftp',
                70 : 'gopher',
                79 : 'finger',
                80 : 'http',
                88 : 'kerberos',
               102 : 'ms exchange',
               110 : 'pop3',
               113 : 'ident',
               119 : 'nntp',
               123 : 'ntp',
               135 : 'epmap',
               137 : 'netbios',
               138 : 'netbios',
               139 : 'netbios',
               143 : 'imap',
               161 : 'snmp',
               162 : 'snmp',
               201 : 'appletalk',
               381 : 'hp openview',
               382 : 'hp openview',
               383 : 'hp openview',
               443 : 'https',
               445 : 'ad/smb',
               464 : 'kerberos',
               465 : 'smtp w/ ssl',
               497 : 'retrospect',
               512 : 'rexec',
               513 : 'relogin',
               514 : 'syslog',
               546 : 'dhcpv6',
               547 : 'dhcpv6',
               587 : 'smtp',
               591 : 'filemaker',
               691 : 'ms exchange',
               902 : 'vmware server',
               989 : 'ftp w/ ssl',
               990 : 'ftp w/ ssl',
               993 : 'imap w/ ssl',
               995 : 'pop3 w/ ssl',
              1026 : 'windows messenger',
              1027 : 'windows messenger',
              1028 : 'windows messenger',
              1029 : 'windows messenger',
              1194 : 'openvpn',
              1241 : 'nessus',
              1433 : 'ms sql',
              1434 : 'ms sql',
              1512 : 'WINS',
              1812 : 'radius',
              1813 : 'radius',
              2082 : 'cpanel',
              2083 : 'cpanel',
              2483 : 'oracle db',
              2484 : 'oracle db',
              2967 : 'symantec av',
              3124 : 'http proxy',
              3128 : 'http proxy',
              3306 : 'mysql',
              3389 : 'terminal',
              3690 : 'subversion',
              4333 : 'msql',
              5000 : 'upnp',
              5432 : 'postgresql',
              5500 : 'vnc server',
              5800 : 'vnc over http',
              8080 : 'http proxy',
              8086 : 'kaspersky av',
              8087 : 'kaspersky av',
              8200 : 'vmware server',
              }

